### ISSUE TITLE
Add support for a custom PR template description used by gh-prx

### ISSUE THREAD

**Issue by dougnukem** [ilaif/gh-prx#19]
Support a Go-template PR template that is used by `gh prx` separate from the github repositories default location. This would allow users of `gh prx` CLI to create templated pull-requests but also allow users to create pull-requests from the Web UI using a non-templated markdown template.

```
.github/PULL_REQUEST_TEMPLATE.md
```

E.g. ideally a user could specify in their `.github/.gh-prx.yaml`

```
pr:
   title: "{{.Type}}{{.Prefix}}{{with .Issue}}({{.}}){{end}}: {{humanize .Description}}" # PR title template
   ignore_commits_patterns: ["^wip"] # Patterns to filter out a commits from the {{.Commits}} variable
   answer_checklist: false # Whether to prompt the user to answer PR description checklists. Possible answers: yes, no, skip (remove the item)
   push_to_remote: true # Whether to push the local changes to remote before creating the PR
issue:
   provider: jira # The provider to use for fetching issue details (supported: github,jira,linear)
   types: ["fix", "feat", "chore", "docs", "refactor", "test", "style", "build", "ci", "perf", "revert"] # The issue types to prompt the user when creating a new branch
   pull_request_template: .github/PULL_REQUEST_TEMPLATE.ghprx.md # default is .github/PULL_REQUEST_TEMPLATE.md
   ignore_pull_request_template: false # If true, the pull request template in the repository will be ignored.
```

**Comment by ilaif** [comment]
Hi @dougnukem 
I'm terribly sorry for the long wait.

I've implemented those changes for you. Please note that `pull_request_template_path` is now in the **root** of the config, i.e.:
```yaml
pr:
  ...
issue:
  ...
pull_request_template_path: <your_custom_path_from_repo_root>
```

Let me know if that solves your use case!
